#ifndef EFFECTS_H
#define EFFECTS_H

/*******************************************************************************
 * STUDENT: Jaunie Williams, Edward Montilla                                   *
 *                                                                             *
 * COURSE: COMP2659 - COMPUTING MACHINERY II                                   *
 *                                                                             *
 * PROFESSOR: Marc Schroeder								                   *
 * 																			   *
 * PURPOSE: Responsible for sound effects.									   *
 *                                                                             *
 *******************************************************************************/

#include "TYPES.H"

void play_gunshot();
void play_flaps();
void play_explosion();

#endif
