#include "EVENTS.H"

/*******************************************************************************
 * STUDENT: Jaunie Williams, Edward Montilla                                   *
 *                                                                             *
 * COURSE: COMP2659 - COMPUTING MACHINERY II                                   *
 *                                                                             *
 * PROFESSOR: Marc Schroeder								                   *
 * 																			   *
 * PURPOSE: Handles input.                                                     *
 *                                                                             *
 *******************************************************************************/

void read_key(int key, const Model *model);