tst_rast: tst_rast.o raster.o events.o model.o rast_asm.o
	cc68x -g tst_rast.o raster.o events.o model.o rast_asm.o -o tst_rast

tst_rast.o: tst_rast.c raster.h events.h
	cc68x -g -c tst_rast.c

events.o: events.c events.h model.h
	cc68x -g -c events.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

model.o: model.c model.h
	cc68x -g -c model.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s
